### PR TITLE
Command line arguments parsing

### PR DESCRIPTION
**Pull request by ArtemiyGranat**

### CODE REVIEW

**Comment by ArtemiyGranat** [comment]
Not sure what would be better: to pass the whole `config` to the `brute_iter ()` and `brute_rec_wrapper ()` functions or `config.length` and `config.alphabet` separately.

**Review by hnarkaytis — APPROVED** [review]
LGTM

**Comment by hnarkaytis** [comment]
Next step:
Refactor void brute_iter (char *password, char *alph, int length) and brute_rec_wrapper to:
bool brute_iter (char *password, config_t * config, password_handler_t password_handler, void * context)

typedef bool (*password_handler_t) (char * password, void * context);

brute_{iter|rec} should generate passwords and trigger a callback password_handler. password handler return boolean to indicate that iterations should be completed or interrupted. 

After that add one more parameter to command line (-h hash) and store it into config_t. Implement password handler that will calculate and compare hash using linux passwd file hashing function. More info here https://linux.die.net/man/3/crypt_r

**Comment by ArtemiyGranat** [comment]
> Next step: Refactor void brute_iter (char *password, char *alph, int length) and brute_rec_wrapper to: bool brute_iter (char *password, config_t * config, password_handler_t password_handler, void * context)
> 
> typedef bool (*password_handler_t) (char * password, void * context);
> 
> brute_{iter|rec} should generate passwords and trigger a callback password_handler. password handler return boolean to indicate that iterations should be completed or interrupted.
> 
> After that add one more parameter to command line (-h hash) and store it into config_t. Implement password handler that will calculate and compare hash using linux passwd file hashing function. More info here https://linux.die.net/man/3/crypt_r

Got it. Also, should I check if user passed the `-l` flag correctly or not? As I remember, `atoi ()` returns 0 if there is an error. I could write something like this:
```
if (config->length == 0) 
  {
    return -1;
  }
```

**Comment by hnarkaytis** [comment]
Yes, it make sense to add guardrails for all command line parameters with some human readable error messages.

**Comment by ArtemiyGranat** [comment]
> Yes, it make sense to add guardrails for all command line parameters with some human readable error messages.

Ok. Should I add some output like "Password found/not found" based on brute force result?

**Pull request merged**
